# Generated by Django 4.2.3 on 2024-10-09 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiQuityapp', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'role')},
        ),
    ]
