# Generated by Django 4.2.3 on 2024-10-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiQuityapp', '0005_user_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
