# Generated by Django 4.2.3 on 2024-10-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiQuityapp', '0006_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_sent_for_approval',
            field=models.BooleanField(default=False),
        ),
    ]
