# Generated by Django 4.2.3 on 2024-10-12 04:13

import ArtiQuityapp.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiQuityapp', '0008_user_reset_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[ArtiQuityapp.validations.ValidatePrice]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, validators=[ArtiQuityapp.validations.ValidateEmail]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[ArtiQuityapp.validations.ValidateName]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[ArtiQuityapp.validations.ValidateName]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[ArtiQuityapp.validations.ValidateUserName]),
        ),
    ]
