# Generated by Django 4.2.3 on 2024-10-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtiQuityapp', '0010_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.AddField(
            model_name='payment',
            name='courses',
            field=models.ManyToManyField(related_name='payments', to='ArtiQuityapp.course'),
        ),
    ]
